import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'public/prof/css/global/buttons.css',
                'public/prof/css/global/editor.css',
                'public/prof/css/global/footer.css',
                'public/prof/css/global/global.css',
                'public/prof/css/global/header.css',
                'public/prof/css/global/humburger-menu.css',
                'public/prof/css/global/icons.css',
                'public/prof/css/pages/article/archive.css',
                'public/prof/css/pages/article/single.css',
                'public/prof/css/pages/portfolio/archive.css',
                'public/prof/css/pages/portfolio/single.css',
                'public/prof/css/pages/portfolio/sticky-journal.css',
                'public/prof/css/pages/portfolio/template-journal.css',
                'public/prof/css/parts/card-portfolio.css',
                'public/prof/css/parts/card-post.css',
                'public/prof/css/parts/comments.css',
                'public/prof/css/parts/forms.css',
                'public/prof/css/parts/pagination.css',
                'public/prof/css/parts/widgets.css',
                'public/prof/css/sections/section-banner.css',
                'public/prof/css/sections/section-ceo.css',
                'public/prof/css/sections/section-channels.css',
                'public/prof/css/sections/section-content.css',
                'public/prof/css/sections/section-contentz.css',
                'public/prof/css/sections/section-faq.css',
                'public/prof/css/sections/section-grid.css',
                'public/prof/css/sections/section-hero.css',
                'public/prof/css/sections/section-history.css',
                'public/prof/css/sections/section-itemsgrow.css',
                'public/prof/css/sections/section-leap.css',
                'public/prof/css/sections/section-logos.css',
                'public/prof/css/sections/section-map.css',
                'public/prof/css/sections/section-portfolio.css',
                'public/prof/css/sections/section-portfoliosimple.css',
                'public/prof/css/sections/section-portfolioz.css',
                'public/prof/css/sections/section-services.css',
                'public/prof/css/sections/section-solution.css',
                'public/prof/css/sections/section-team.css',
                'public/prof/css/sections/section-teamcard.css',
                'public/prof/css/sections/section-timeline.css',
                'public/prof/css/vendors/swiper.css'
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
});
